config/routes.rb
Rails.application.routes.draw do
  
  resources :clients, path: "customers"

  delete 'clients/delete-all', to: "clients#delete_all", as: "supprime-tout"

	#TODO
  # resources :glaces

  get 'accueil/choix'
  get 'accueil/commander'
  get 'accueil/payer'

  get 'livrer-moi-vite', to: "accueil#livrer_moi_way"
  get 'palayaa', to: "accueil#palayaa"

  # get    '/glaces',     to: "glaces#index"
  # get    '/glaces/new', to: "glaces#new"
  # post   '/glaces',     to: "glaces#create"
  # get    'glaces/:id',  to: "glaces#show"
  # put    'glaces/:id',  to: "glaces#edit"
  # delete 'glaces/:id',  to: "glaces#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/choix.rb
class Choix < ApplicationRecord
  belongs_to :glace
  belongs_to :commande
  has_and_belongs_to_many :parfums

  validates_presence_of :quantite
end

app/models/client.rb
class Client < ApplicationRecord
	# self.table_name = "customers" 

	has_many :commandes
end

app/models/commande.rb
class Commande < ApplicationRecord
  belongs_to :client
  has_many :choixes
end

app/models/glace.rb
class Glace < ApplicationRecord
	has_many :choixes
end

app/models/parfum.rb
class Parfum < ApplicationRecord
  has_and_belongs_to_many :choixes
end

app/controllers/accueil_controller.rb
class AccueilController < ApplicationController
  def choix
  	@message     = "Bienvenue chez Mamamia"
  	@liste_choix = ["Pistache", "Vanille", "Choco", "Fraise", "Yaourt", "Forêt Noire", "Mamamia", "Kinder Bueno"]
  	render 'meschoix'
  end

  def commander
  	# redirect_to
  end

  def palayaa 
  end

  def payer

  end

  # def livrer_moi_way
  # 	@montant_total = 14000
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :def_salamek

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    # respond_to do |format|
    #   format.html { redirect_to client_url(@client.id), notice: 'Client was successfully created.' }
    #   format.json { render :show, status: :created, location: @client }
    # end
  end

  def delete_all
    Client.delete_all
    redirect_to clients_path, notice: 'All customers are now deleted' 
  end
  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client.id), notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client.id), notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { 
        redirect_to clients_url, 
        notice: 'Client was successfully destroyed.' 
      }
      format.json { head :no_content }
    end
  end

  private

    def def_salamek
      @salam = "Bonjour/Salam/Mbada/Salut/Kasumay ..."
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).require(:nom)
      params.require(:client).permit(:nom, 
        :prenom, 
        :adresse, 
        :numero_telephone,
        :email
      )
    end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/accueil/_choix.html.erb
<h1>Accueil#choix</h1>
<h2>Kaaay def sa choix</h2>

<%= @message %>
<table>
<% @liste_choix.each do |el|  %>
	<tr> <td><%= el %> </td></tr>
<% end %>
</table>

<p>Find me in app/views/accueil/choix.html.erb</p>

app/views/accueil/commander.html.erb
<h1>Accueil#commander</h1>
<p>Find me in app/views/accueil/commander.html.erb</p>

app/views/accueil/livrer_moi_way.html.erb
Le montant total de la livraison est: <%= @montant_total%>

app/views/accueil/meschoix.html.erb
<h1>J'affiche mes choix</h1>

app/views/accueil/payer.html.erb
<p id="notice"><%= notice %></p>

<h1>Accueil#payer</h1>
<p>Find me in app/views/accueil/payer.html.erb</p>

app/views/clients/_form.html.erb
<h1><%= client.inspect %></h1>

<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nom %>
    <%= form.text_field :nom %>
  </div>

  <div class="field">
    <%= form.label :prenom %>
    <%= form.text_field :prenom %>
  </div>

  <div class="field">
    <%= form.label :adresse %>
    <%= form.text_field :adresse %>
  </div>

  <div class="field">
    <%= form.label :numero_telephone %>
    <%= form.text_field :numero_telephone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<%= link_to 'Yakatiii ! ', supprime_tout_path, method: 'delete'  , data: {confirm: 'Voulez vous vraiment supprimer ?'} %>
<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Adresse</th>
      <th>Numero telephone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.nom %></td>
        <td><%= client.prenom %></td>
        <td><%= client.adresse %></td>
        <td><%= client.numero_telephone %></td>
        <td><%= client.email %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>Formulaire de création</h1>

<%= render 'form', client: @client, message: "dodo" %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @client.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @client.prenom %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @client.adresse %>
</p>

<p>
  <strong>Numero telephone:</strong>
  <%= @client.numero_telephone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mamamia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>